/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokedex.inicio;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Artzaint
 */
public class EditarPokemon extends javax.swing.JFrame {
    /**
     * Creates new form Visualizar
     */
    private Integer id;
    private String nombrePokemon;
    private ButtonGroup bg = new ButtonGroup();
    private String[] oldValues = new String[2];
    
    public EditarPokemon(int id, String pokemon) {
        initComponents();
        bg.add(macho);
        bg.add(hembra);
        bg.add(noTiene);
        this.id = id;
        this.nombrePokemon = pokemon;
        setSelected();
    }
    
    public EditarPokemon() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(macho);
        bg.add(hembra);
        bg.add(noTiene);
        macho.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Apodo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mov1 = new javax.swing.JComboBox<>();
        mov2 = new javax.swing.JComboBox<>();
        mov3 = new javax.swing.JComboBox<>();
        mov4 = new javax.swing.JComboBox<>();
        hembra = new javax.swing.JRadioButton();
        macho = new javax.swing.JRadioButton();
        noTiene = new javax.swing.JRadioButton();
        tipo1 = new javax.swing.JComboBox<>();
        tipo2 = new javax.swing.JComboBox<>();
        region = new javax.swing.JComboBox<>();
        pokemon1 = new javax.swing.JTextField();
        habilidad = new javax.swing.JComboBox<>();
        apodo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Fondo4 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Pokemon:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 40, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Movimientos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Habilidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("Genero:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        Apodo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        Apodo.setText("Apodo:");
        getContentPane().add(Apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Región:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        mov1.setModel(new javax.swing.DefaultComboBoxModel<>(cargarMovimientos()));
        mov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mov1ActionPerformed(evt);
            }
        });
        getContentPane().add(mov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, -1));

        mov2.setModel(new javax.swing.DefaultComboBoxModel<>(cargarMovimientos()));
        getContentPane().add(mov2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 130, -1));

        mov3.setModel(new javax.swing.DefaultComboBoxModel<>(cargarMovimientos()));
        getContentPane().add(mov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, -1));

        mov4.setModel(new javax.swing.DefaultComboBoxModel<>(cargarMovimientos()));
        getContentPane().add(mov4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 130, -1));

        hembra.setBackground(new java.awt.Color(203, 240, 240));
        hembra.setText("Hembra");
        getContentPane().add(hembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        macho.setBackground(new java.awt.Color(203, 240, 240));
        macho.setText("Macho");
        macho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machoActionPerformed(evt);
            }
        });
        getContentPane().add(macho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        noTiene.setBackground(new java.awt.Color(203, 240, 240));
        noTiene.setText("No tiene");
        getContentPane().add(noTiene, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        tipo1.setModel(new javax.swing.DefaultComboBoxModel<>(SQLusuarios.getTipos()));
        getContentPane().add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 70, -1));

        tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(SQLusuarios.getTipos()));
        getContentPane().add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 70, -1));

        region.setModel(new javax.swing.DefaultComboBoxModel<>(SQLusuarios.getRegiones()));
        getContentPane().add(region, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        getContentPane().add(pokemon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, -1));

        habilidad.setModel(new javax.swing.DefaultComboBoxModel<>(SQLusuarios.getHabilidades()));
        getContentPane().add(habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, -1));
        getContentPane().add(apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, -1));

        Fondo4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\Fondo2.png"));
        getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void machoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrincipal newframe = new MenuPrincipal(id);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = pokemon1.getText().trim();
        String apodo = this.apodo.getText().trim();
        String tipo1 = this.tipo1.getSelectedItem().toString();
        String tipo2 = this.tipo2.getSelectedItem().toString();
        String region = this.region.getSelectedItem().toString();
        String habilidad = this.habilidad.getSelectedItem().toString();
        String genero = macho.isSelected() ? "0" : (hembra.isSelected() ? "1" : "2");
        String[] movimientos = {mov1.getSelectedItem().toString(), mov2.getSelectedItem().toString(),
            mov3.getSelectedItem().toString(), mov4.getSelectedItem().toString()};
        
        System.out.println(genero); 
        
        if(nombre.equals(null) || tipo1.equals(tipo2) || tipo1.equals("-") 
                || movimientos[0].equals(movimientos[1])
                || movimientos[1].equals(movimientos[2]) || movimientos[2].equals(movimientos[3])){
            JOptionPane.showMessageDialog(this, "El pokémon ingresado es inválido. Revise que:\n"
                    + "1. Ni el nombre ni el apodo estén vacíos.\n"
                    + "2. Los tipos no sea iguales.\n"
                    + "3. El tipo 1 no sea nulo.\n"
                    + "4. No hayan ataques iguales.");
        }
        else if(SQLusuarios.editarPokemon(nombre, apodo, genero, id, habilidad, region, tipo1, tipo2, movimientos, oldValues)){
            JOptionPane.showMessageDialog(this, "¡Pokémon editado!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al editar el Pokémon.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private String[] cargarMovimientos(){
        String[] movs = SQLusuarios.getMovimientos();
        if(movs == null){
            JOptionPane.showMessageDialog(this, "Ocurrió un error al cargar los movimientos.");
            return null;
        }
        return movs;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPokemon().setVisible(true);
            }
        });
    }
    
    private void setSelected(){
        String[] movimientos = SQLusuarios.getMovimientosDe(id,nombrePokemon);
        mov1.setSelectedItem(movimientos[0]);
        mov2.setSelectedItem(movimientos[1]);
        mov3.setSelectedItem(movimientos[2]);
        mov4.setSelectedItem(movimientos[3]);
        
        String[] tipos = SQLusuarios.getTiposDe(id,nombrePokemon);
        tipo1.setSelectedItem(tipos[0]);
        tipo2.setSelectedItem(tipos[1]);
        
        String[] otros = SQLusuarios.getOtrosDe(id,nombrePokemon);
        pokemon1.setText(otros[0]);
        apodo.setText(otros[1]);
        region.setSelectedItem(otros[2]);
        habilidad.setSelectedItem(otros[3]);
        
        if(otros[4].equals("0"))
            macho.setSelected(true);
        else if(otros[4].equals("1"))
            hembra.setSelected(true);
        else
            noTiene.setSelected(true);
        
        oldValues[0] = otros[0];
        oldValues[1] = otros[1];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apodo;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JTextField apodo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> habilidad;
    private javax.swing.JRadioButton hembra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton macho;
    private javax.swing.JComboBox<String> mov1;
    private javax.swing.JComboBox<String> mov2;
    private javax.swing.JComboBox<String> mov3;
    private javax.swing.JComboBox<String> mov4;
    private javax.swing.JRadioButton noTiene;
    private javax.swing.JTextField pokemon1;
    private javax.swing.JComboBox<String> region;
    private javax.swing.JComboBox<String> tipo1;
    private javax.swing.JComboBox<String> tipo2;
    // End of variables declaration//GEN-END:variables
}
