/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokedex.inicio;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Artzaint
 */

public class EditarAvatar extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    private Integer id;
    private String nombreUsuario;
    public EditarAvatar(Integer id) {
        this.id = id;
        initComponents();
        cargarInfo();
    }
    
    public EditarAvatar() {
        initComponents();
        cargarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelVentanaRegistro = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        SelectorDeGenero = new javax.swing.JComboBox<>();
        FinalizarRegistro = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokedex: Registro de Entrenador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelVentanaRegistro.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        LabelVentanaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LabelVentanaRegistro.setText("Cambiar datos");
        LabelVentanaRegistro.setToolTipText("");
        LabelVentanaRegistro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(LabelVentanaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        LabelUsuario.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(240, 240, 240));
        LabelUsuario.setText("Usuario");
        getContentPane().add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 88, -1));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 188, 31));

        LabelNombre.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(240, 240, 240));
        LabelNombre.setText("Nombre");
        getContentPane().add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 188, 31));

        LabelPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(240, 240, 240));
        LabelPassword.setText("Contraseña");
        getContentPane().add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 188, 31));
        ShowPassword.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                contrasena.setEchoChar((char) 0);
            } else {
                contrasena.setEchoChar('*');
            }
        });

        ShowPassword.setBackground(new java.awt.Color(204, 0, 51));
        ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword.setText("Mostrar Contraseña");
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 280, 140, -1));

        SelectorDeGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SelectorDeGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su Genero", "Hombre", "Mujer" }));
        getContentPane().add(SelectorDeGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 30));

        FinalizarRegistro.setBackground(new java.awt.Color(204, 0, 0));
        FinalizarRegistro.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        FinalizarRegistro.setText("Actualizar");
        FinalizarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(FinalizarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 275, 131, 30));

        Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Regresar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));

        jButton1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 30));

        Fondo2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\Fondo1.jpg"));
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        MenuPrincipal newframe = new MenuPrincipal(this.id);
        newframe.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void FinalizarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarRegistroActionPerformed
        String genero = SelectorDeGenero.getSelectedItem().toString().equals("Hombre") ? "0" : "1";
        if(SQLusuarios.editarUsuario(id,nombre.getText(),usuario.getText(),contrasena.getText(), genero, this.nombreUsuario)){
            JOptionPane.showMessageDialog(this, "¡Usuario modificado!");
            RegresarActionPerformed(null);
        }
        else
            JOptionPane.showMessageDialog(this, "¡Ocurrió un error al modificar su usuario.");
    }//GEN-LAST:event_FinalizarRegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(SQLusuarios.eliminarUsuario(id)){
            JOptionPane.showMessageDialog(this, "Su usuario ha sido eliminado.");
            InicioDeSesion newframe = new InicioDeSesion();
            newframe.setVisible (true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "No se ha podido eliminar su usuario.");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditarAvatar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalizarRegistro;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel LabelVentanaRegistro;
    private javax.swing.JButton Regresar;
    private javax.swing.JComboBox<String> SelectorDeGenero;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private void cargarInfo() {
        String[] info = SQLusuarios.getInfoUsuario(id);
        nombre.setText(info[0]);
        usuario.setText(info[1]);
        nombreUsuario = info[1];
        contrasena.setText(info[2]);
        SelectorDeGenero.setSelectedItem(info[3].equals("0")?"Hombre":"Mujer");
    }
}
