/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokedex.inicio;

/**
 *
 * @author Artzaint
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private int id;
    static void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(int id) {
        this.id = id;
        initComponents();
    }
    
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        VerPokes = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();
        VerPokes1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        VerPokes2 = new javax.swing.JButton();
        Fondo3 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokedex: Menu Principal");
        setMinimumSize(new java.awt.Dimension(430, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerPokes.setBackground(new java.awt.Color(204, 255, 255));
        VerPokes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        VerPokes.setText("Registro");
        VerPokes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPokesActionPerformed(evt);
            }
        });
        getContentPane().add(VerPokes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 40));
        System.out.println("ID: " + this.id);

        CerrarSesion.setBackground(new java.awt.Color(204, 255, 255));
        CerrarSesion.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        CerrarSesion.setText("Cerrar");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 70, 30));

        VerPokes1.setBackground(new java.awt.Color(204, 255, 255));
        VerPokes1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        VerPokes1.setText("Visualizar");
        VerPokes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPokes1ActionPerformed(evt);
            }
        });
        getContentPane().add(VerPokes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 40));

        jButton1.setText("Cambiar datos de avatar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, 30));

        VerPokes2.setBackground(new java.awt.Color(204, 255, 255));
        VerPokes2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        VerPokes2.setText("Lista");
        VerPokes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPokes2ActionPerformed(evt);
            }
        });
        getContentPane().add(VerPokes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 40));

        Fondo3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\Fondo2.png"));
        getContentPane().add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
      InicioDeSesion newframe = new InicioDeSesion();
        newframe.setVisible (true);
            this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void VerPokesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPokesActionPerformed
        RegistroPKMN newframe = new RegistroPKMN(this.id);
        newframe.setVisible (true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VerPokesActionPerformed

    private void VerPokes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPokes2ActionPerformed
        Lista newframe = new Lista(this.id);
        newframe.setVisible (true);
            this.dispose();        

    }//GEN-LAST:event_VerPokes2ActionPerformed

    private void VerPokes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPokes1ActionPerformed
        Visualizar newframe = new Visualizar(id);
        newframe.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_VerPokes1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EditarAvatar newframe = new EditarAvatar(id);
        newframe.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JButton VerPokes;
    private javax.swing.JButton VerPokes1;
    private javax.swing.JButton VerPokes2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
