/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokedex.inicio;

import javax.swing.JOptionPane;

/**
 *
 * @author Artzaint
 */
public class Visualizar extends javax.swing.JFrame {

    /**
     * Creates new form Visualizar
     */
    private Integer id;
    
    public Visualizar(int id){
        this.id = id;
        initComponents();
        seleccionActionPerformed(null);
    }
    
    public Visualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        apodo = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        numeroPokedex = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        region = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        mov1 = new javax.swing.JLabel();
        mov2 = new javax.swing.JLabel();
        mov3 = new javax.swing.JLabel();
        mov4 = new javax.swing.JLabel();
        pokemon = new javax.swing.JLabel();
        habilidad = new javax.swing.JLabel();
        seleccion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        btnMov4 = new javax.swing.JButton();
        btnHabilidad = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnMov3 = new javax.swing.JButton();
        hab = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        btnMov2 = new javax.swing.JButton();
        btnMov1 = new javax.swing.JButton();
        Fondo4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apodo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        apodo.setText("Apodo:");
        getContentPane().add(apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        tipo1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tipo1.setText("Tipo:");
        getContentPane().add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, -1));

        numeroPokedex.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        numeroPokedex.setText("ID: ");
        getContentPane().add(numeroPokedex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 20));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Movimientos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("Descripcion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        region.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        region.setText("Región:");
        getContentPane().add(region, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, -1));

        genero.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        genero.setText("Genero:");
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 20));

        mov1.setText("-");
        getContentPane().add(mov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 200, -1));

        mov2.setText("-");
        getContentPane().add(mov2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, -1));

        mov3.setText("-");
        getContentPane().add(mov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));

        mov4.setText("-");
        getContentPane().add(mov4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));

        pokemon.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        pokemon.setText("Pokemon:");
        getContentPane().add(pokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        habilidad.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, -1));

        seleccion.setBackground(new java.awt.Color(204, 255, 255));
        seleccion.setModel(new javax.swing.DefaultComboBoxModel<>(SQLusuarios.getPokemon(id)));
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });
        getContentPane().add(seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 130, -1));

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(204, 255, 255));
        descripcion.setColumns(20);
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.setText("\n");
        descripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 90));

        btnMov4.setBackground(new java.awt.Color(203, 240, 240));
        btnMov4.setText("i");
        btnMov4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMov4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMov4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 20, 20));

        btnHabilidad.setBackground(new java.awt.Color(203, 240, 240));
        btnHabilidad.setText("i");
        btnHabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 20, 20));

        jButton8.setBackground(new java.awt.Color(203, 240, 240));
        jButton8.setText("Regresar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, 20));

        btnMov3.setBackground(new java.awt.Color(203, 240, 240));
        btnMov3.setText("i");
        btnMov3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMov3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 20, 20));

        hab.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        hab.setText("Habilidad: ");
        getContentPane().add(hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 150, 20));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 20, 20));

        btnMov2.setBackground(new java.awt.Color(203, 240, 240));
        btnMov2.setText("i");
        btnMov2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMov2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMov2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 20, 20));

        btnMov1.setBackground(new java.awt.Color(203, 240, 240));
        btnMov1.setText("i");
        btnMov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMov1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 20, 20));

        Fondo4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\Fondo2.png"));
        getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        // TODO add your handling code here:
        String nombre = seleccion.getSelectedItem().toString();
        String[] movimientos = SQLusuarios.getMovimientosDe(id,nombre);
        mov1.setText(movimientos[0]);
        mov2.setText(movimientos[1]);
        mov3.setText(movimientos[2]);
        mov4.setText(movimientos[3]);
        
        String[] tipos = SQLusuarios.getTiposDe(id,nombre);
        tipo1.setText("Tipo: " + tipos[0] + " " + tipos[1]);
        
        String[] otros = SQLusuarios.getOtrosDe(id,nombre);
        pokemon.setText("Pokemon: " + otros[0]);
        apodo.setText("Apodo: " + otros[1]);
        region.setText("Región: " + otros[2]);
        hab.setText(otros[3]);
        genero.setText("Género: " + (otros[4].equals("0") ? "Macho" : otros[4].equals("1") ? "Hembra" : "No tiene"));
        numeroPokedex.setText("ID: " + otros[5]);
    }//GEN-LAST:event_seleccionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MenuPrincipal newframe = new MenuPrincipal(id);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnHabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadActionPerformed
        String texto = SQLusuarios.getInfoDeHabilidad(hab.getText());
        descripcion.setText(texto);
    }//GEN-LAST:event_btnHabilidadActionPerformed

    private void btnMov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMov1ActionPerformed
        descripcion.setText(SQLusuarios.getInfoDeMov(mov1.getText()));
    }//GEN-LAST:event_btnMov1ActionPerformed

    private void btnMov2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMov2ActionPerformed
        descripcion.setText(SQLusuarios.getInfoDeMov(mov2.getText()));
    }//GEN-LAST:event_btnMov2ActionPerformed

    private void btnMov3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMov3ActionPerformed
        descripcion.setText(SQLusuarios.getInfoDeMov(mov3.getText()));
    }//GEN-LAST:event_btnMov3ActionPerformed

    private void btnMov4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMov4ActionPerformed
        descripcion.setText(SQLusuarios.getInfoDeMov(mov4.getText()));
    }//GEN-LAST:event_btnMov4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo4;
    private javax.swing.JLabel apodo;
    private javax.swing.JButton btnHabilidad;
    private javax.swing.JButton btnMov1;
    private javax.swing.JButton btnMov2;
    private javax.swing.JButton btnMov3;
    private javax.swing.JButton btnMov4;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel hab;
    private javax.swing.JLabel habilidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mov1;
    private javax.swing.JLabel mov2;
    private javax.swing.JLabel mov3;
    private javax.swing.JLabel mov4;
    private javax.swing.JLabel numeroPokedex;
    private javax.swing.JLabel pokemon;
    private javax.swing.JLabel region;
    private javax.swing.JComboBox<String> seleccion;
    private javax.swing.JLabel tipo1;
    // End of variables declaration//GEN-END:variables
}
